### ISSUE TITLE
Immutable Progressbar Value

### ISSUE THREAD

**Issue by Synth9283** [trustable-code/NiGui#100]
Greetings, I have lately started using the NiGui library. However, I have recently encountered a problem where I am not able to change the `progressbar.value` as displayed [here](https://github.com/trustable-code/NiGui/blob/master/examples/example_02_controls.nim) on line 26 inside a for loop with an onButtonClick event

**Comment by 0xACE** [comment]
This report is not helpful?

Which os are you on?

Please provide a minimal example showing the error.

The link you provided is working as expected.

**Comment by Synth9283** [comment]
OS: Arch Linux
Example:
```nim
import nigui

app.init()

var window = newWindow()

var container = newLayoutContainer(Layout_Vertical)
window.add(container)

# Adds a button
var loadButton = newButton("Load")
container.add(loadButton)

# Add a Progress Bar control:
var progressBar = newProgressBar()
container.add(progressBar)

# When load button is clicked
loadButton.onClick = proc(event: ClickEvent) =
    for i in 0..100:
        progressBar.value += float(0.01)

window.show()
app.run()
```

**Comment by SolitudeSF** [comment]
`value` is a procedure, not a field.
`progressBar.value = progressBar.value + 0.01`

**Comment by Synth9283** [comment]
It works! Thank you very much! I am very sorry about this
