### ISSUE TITLE
Example-1 image

### ISSUE THREAD

**Issue by Arthur-Palhano** [trustable-code/NiGui#106]
Here is a print of the example-1 code, the actual image is a funny face lol.
![image](https://user-images.githubusercontent.com/49375534/89927300-82162980-dbdc-11ea-819f-e3f1b63ea489.png)

**Comment by trustable-code** [comment]
What is the question or the bug of this issue?

**Comment by Arthur-Palhano** [comment]
Sorry, there is no error or bug, I just added a screenshot of the example proposed in example-1, the image that is currently there is an emoji.

**Comment by Arthur-Palhano** [comment]
It can be said that the "error" is in the documentation

**Comment by Arthur-Palhano** [comment]
Sorry man, I saw now that the [image](https://raw.githubusercontent.com/trustable-code/NiGui/master/examples/example_01_basic_app.png) in example-1 was for the window icon. I thought it was to show a screenshot of the application

**Comment by trustable-code** [comment]
Thanks for clarification.
