### ISSUE TITLE
Crash on windows server 2012R2 ; pEnableHighDpiSupport ; SIGSEGV: Illegal storage access

### ISSUE THREAD

**Issue by enthus1ast** [trustable-code/NiGui#109]
Crash on windows server 2012:
```
C:\Users\Administrator\.nimble\pkgs\nigui-0.2.4\nigui\private\windows\platform_impl.nim(402) init
C:\Users\Administrator\.nimble\pkgs\nigui-0.2.4\nigui\private\windows\platform_impl.nim(387) pEnableHighDpiSupport
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by trustable-code** [comment]
It calls the WinAPI function `GetDpiForWindow()`. According to https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow it's not available on Windows Server. To avoid the crash, I have added a nil pointer check. Can you please confirm that the fix works for you?

**Comment by enthus1ast** [comment]
yes, thank you
