### ISSUE TITLE
iOS & Android

### ISSUE THREAD

**Issue by janjaapbos** [trustable-code/NiGui#11]
Would it make sense, or be possible at all, to also include support for Android & iOS?

**Comment by PMunch** [comment]
Possible? Perhaps. Many of the same controls (Buttons, Checkboxes, lists, etc.) exists on mostly all platforms so it's not impossible.

Make sense? Not so sure. Android/iOS devices are typically a quite different kind of interface than computers. So it might be weird to have a 1:1 toolkit for mobile and PC. Maybe something like web where you can design different interfaces for different screen sizes etc. would work but even that might be a bit weird.

The best solution IMHO would be to have a common event system with different graphical toolkits. So I would write an application code with logic that works for some input and output of events and then I could create different interfaces for the different targets. To ease the creation you could use something like NiGUI that can create similar GUIs for multiple similar platforms but in the end the code logic would be separated from the GUI code.

**Comment by janjaapbos** [comment]
Thanks for the feedback!

**Comment by trustable-code** [comment]
We can discuss this topic somewhere in the future again, first I like to finish the public API, documentation and the support for windows, gtk and macOS. This will take a while.

**Comment by PMunch** [comment]
That's probably a good idea. I might look into creating a common event system for various toolkits separate from this which would allow this project to focus on desktop platforms and then maybe have something similar focused on mobile platforms.
