### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by theAkito** [trustable-code/NiGui#127]
I see that the newest release is of version 0.2.4 and that is a very old one. Is there a good reason why there is no newer version?

For example, if you install this module purely through `nimble install nigui`, you cannot cross-compile to Windows:

```
x86_64-w64-mingw32-gcc: error: \home\akito\.nimble\pkgs\nigui-0.2.4\nigui\private\windows\manifest_x64.res: No such file or directory
```

Because of:
https://github.com/trustable-code/NiGui/commit/2460ac2190da1154f98523c0060ed3440441a67a

So, I had to get the source from Git and manually run `nimble install`.

Perhaps it would be easier for others if a new version would be released.

**Comment by trustable-code** [comment]
Done, see https://github.com/trustable-code/NiGui/releases/tag/v0.2.5

Thanks for the hint.
