### ISSUE TITLE
Add Combobox OnChange Event

### ISSUE THREAD

**Issue by Dev1lroot** [trustable-code/NiGui#137]
OnChange Event

**Comment by Dev1lroot** [comment]
to make events like:
`
combobox.onChange = proc(event: ChangeEvent) =
  input.text = magicFuction(combobox.value)
`

**Comment by theAkito** [comment]
Something about this stinks like JavaScript.

**Comment by trustable-code** [comment]
Example code:

```nim
comboBox.onChange = proc(event: ComboBoxChangeEvent) =
  echo "ComboBox changed to ", comboBox.value
```
