### ISSUE TITLE
ComboBox Error

### ISSUE THREAD

**Issue by wwderw** [trustable-code/NiGui#148]
The ComboBoxChangeEvent does not appear to be working (or in) the latest version of Nigui.  I had to go back to when ComboBox was first added in order to get the functionality back (I may not have needed to regress that far back, but I did that just to make sure).  

I don't know if this was on purpose if combobox is to be deprecated or if this is bug, just thought I would mention.

Using the latest dev Nim branch on Arch.

**Comment by trustable-code** [comment]
How are you using it?

This example works:
```nim
import nigui

app.init()

var window = newWindow()

var container = newLayoutContainer(Layout_Vertical)
window.add(container)

var comboBox = newComboBox(@["Option 1", "Option 2"])
container.add(comboBox)

comboBox.onChange = proc(event: ComboBoxChangeEvent) =
  echo comboBox.value

window.show()

app.run()
```

**Comment by wwderw** [comment]
Using your exact code, I get error unidentified modifier (which is the same error that I got earlier).

Now, I am on 1.7.1 Dev for Nim.  Would that have any bearing on it?

**Comment by wwderw** [comment]
That seems to have done it from what I can tell.

Thanks!
