### ISSUE TITLE
sample can't be compiled

### ISSUE THREAD

**Issue by r3d9u11** [trustable-code/NiGui#21]
Hi. I tried to compile sample example_02_controls.nim, but compilation was failed:
```
Hint: unicode [Processing]
/home/r3d9u11/.nimble/pkgs/nigui-0.1.0/nigui.nim(927, 24) Error: invalid character constant
```
NiGUI installed via Nimble, Linux Mint 18.2.
What I'm doing wrong?

**Comment by trustable-code** [comment]
You need to update the Nim compiler to the latest release.

**Comment by r3d9u11** [comment]
@trustable-code thank you, with Nim 0.18.0 it works fine!
