### ISSUE TITLE
relative directory to load image does not work

### ISSUE THREAD

**Issue by CodeDoes** [trustable-code/NiGui#22]
```nim
var image1 = newImage()
image1.loadFromFile("example_01_basic_app.png")
```
I don't really understand how to ensure that the image always gets loaded. What settings should I use to run the examples.
note:
    It works with absolute directories. That's not what I'm asking about though

**Comment by trustable-code** [comment]
loadFromFile() passes the file path unchanged to the underlying platform call.
When it's relative, I assume it uses the current working directory.

Maybe you need this:
```nim
image1.loadFromFile(getAppDir() / "example_01_basic_app.png")
```

**Comment by trustable-code** [comment]
If still a problem, please re-open.
