### ISSUE TITLE
Add ability to close window with `Ctrl+Q`

### ISSUE THREAD

**Issue by narimiran** [trustable-code/NiGui#25]
Currently window can be closed with `Alt+F4`. Can `Ctrl+Q` be added, as it is quite common shortcut for that?

**Comment by trustable-code** [comment]
@narimiran 
I think the shortcut should NOT be added in general to NiGui.
But you can do this in your application. I have just implemented it.

Example code:
```nim
window.onKeyDown = proc(event: KeyboardEvent) =
  # Ctrl + Q -> Quit application
  if Key_Q.isDown() and Key_ControlL.isDown():
    app.quit()
```

**Comment by narimiran** [comment]
Thanks for adding it to the examples. I'll close this.
