### ISSUE TITLE
example_01 error

### ISSUE THREAD

**Issue by matkuki** [trustable-code/NiGui#26]
Hi,

Trying to compile `example_01_basic_app.nim` and get:
```
...\.nimble\pkgs\nigui-0.1.0\nigui.nim(951, 41) Error: type mismatch: got <char>
but expected one of:
proc toUpper(c: Rune): Rune
proc toUpper(s: string): string

expression: toUpper(cast[char](unicode))
```
My specs:
- Windows 10 x64
- Nim Compiler Version 0.18.1 [Windows: i386]

**Comment by matkuki** [comment]
Commented out line 66 in `nigui/private/windows/platform_impl.nim` and it works.
Seems like the problem is the recent string implementation change in the compiler.

**Comment by trustable-code** [comment]
@matkuki Thx for reporting :)

**Comment by matkuki** [comment]
Line 66 still needs to be removed!
https://github.com/trustable-code/NiGui/blob/master/src/nigui/private/windows/platform_impl.nim#L66

**Comment by trustable-code** [comment]
@matkuki Why?
I think it's necessary to end the string with two null bytes.

> MultiByteToWideChar does not null-terminate an output string...
https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx

**Comment by matkuki** [comment]
@trustable-code With line 66 uncommented the compilation succeeds, but running the executable throws:
![image](https://user-images.githubusercontent.com/10289651/40986628-fd4dd244-68e6-11e8-96a8-d1babb22556a.png)
commenting out that line makes it work:
![image](https://user-images.githubusercontent.com/10289651/40986712-3045db6a-68e7-11e8-96f5-6bf3b14f9734.png)
Hope it helps.

**Comment by trustable-code** [comment]
@matkuki : I have removed the line, thanks for trying out with latest Nim.
Next time please open a new issue.

**Comment by matkuki** [comment]
@trustable-code Great, thanks! Will open a new issue next time 👍
