### ISSUE TITLE
Changing control font doesn't work on Linux

### ISSUE THREAD

**Issue by matkuki** [trustable-code/NiGui#27]
Hi,

I have a simple app with a textbox and a button in a container.
On Windows, setting the font for either textbox or button works fine, but on Linux nothing happens. The font family and the font size changes have no effect. The code is:
```nim
var textbox = newTextbox("00:00:00")
textbox.fontSize = 50
textbox.fontFamily = "Courier"

var button = newButton("START")
button.width = 100
button.height = 40
button.fontSize = 30
button.fontFamily = "Courier"
```
I am testing on a `Raspberry Pi 3 (Raspbian)` with `Nim Compiler Version 0.18.1 [Linux: arm] Compiled at 2018-05-22`

**Comment by Yardanico** [comment]
Does your device have that font installed?

**Comment by trustable-code** [comment]
It works for me on Manjaro Linux with Xfce and Gtk 3.22

**Comment by matkuki** [comment]
@trustable-code Thanks, tried it on Peppermint with Xfce and it works too. Will look into it some more.
