### ISSUE TITLE
Canvas update

### ISSUE THREAD

**Issue by mzteruru52** [trustable-code/NiGui#28]
![e-2](https://user-images.githubusercontent.com/38907008/43991069-dfe3af6a-9d9f-11e8-88e7-5a51a2f599e7.jpg)
![e-1](https://user-images.githubusercontent.com/38907008/43991073-e2c82986-9d9f-11e8-8363-6000d1a8ff16.JPG)

I want to move this line (on control) when get any input .  
so I searched and tried some ways that I can imagine, but I could not do it.

I think that canvas should update to achieve that.
How can I update canvas?
(I am sorry for my poor English..)

**Comment by trustable-code** [comment]
I think you want to draw a dashed line.
You can draw a dashed line by drawing multiple continuous line.
Maybe this helps: https://saideepdicholkar.blogspot.com/2017/04/bresenhams-line-algorithm-dashed-line.html

**Comment by mzteruru52** [comment]
Thank you for useful hint.
but .. It is not what I want to ask. In other words ,
Can I control position of the line from after displaying window?
[ Windowを表示させた後から、線の位置を移動させることはできるでしょうか？ ]

(If you cannot understand my words, you can ignore this question.)

**Comment by trustable-code** [comment]
OK, I think you need to call the method `forceRedraw`

**Comment by mzteruru52** [comment]
Thank you! I am going to try it.

**Comment by mzteruru52** [comment]
```
  Control.visible=false
  Control.forceRedraw
  Control.visible=true
```

I tried it , then I was able to achieve my purpose!

**Comment by trustable-code** [comment]
I think you don't need the `visible=false` and `visible=true`. Maybe you should first draw into a Bitmap buffer and then draw the Bitmap on the conrol.

**Comment by mzteruru52** [comment]
I see! I will try.
