### ISSUE TITLE
[Question] Is it possible to integrate NiGui with async app?

### ISSUE THREAD

**Issue by TiberiumN** [trustable-code/NiGui#3]
Hi, I have a console async application, is there a possibility to somehow integrate it with NiGui?

**Comment by FedericoCeratto** [comment]
@Yardanico: you closed the issue - is that a yes?

**Comment by Yardanico** [comment]
@FedericoCeratto well, it's indeed possible but a bit "hacky" because you'll need to call poll() manually.
https://github.com/vk-brain/Nickel/blob/755a43b2fa3316e764ffe058aada9ea0fc351da1/src/gui.nim
https://github.com/vk-brain/Nickel/blob/755a43b2fa3316e764ffe058aada9ea0fc351da1/src/vkbot.nim#L298
