### ISSUE TITLE
Windows Compile Fail

### ISSUE THREAD

**Issue by TensorTom** [trustable-code/NiGui#36]
CC: nigui_windows
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing  -IC:\Users\user\bin\nim-0.19.4\lib -o C:\Users\user\nimcache\app_r\nigui_windows.c.o C:\Users\user\nimcache\app_r\nigui_windows.c' failed with exit code: 1

In file included from C:\Users\user\nimcache\app\nigui_windows.c:10:0:
C:\Users\user\bin\nim-0.19.4\lib/nimbase.h:490:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by TensorTom** [comment]
Had to compile with --cpu:i386

**Comment by trustable-code** [comment]
This seems to be a problem between Nim and GCC.
What version of Nim are you using? (``nim --v``)

**Comment by UNIcodeX** [comment]
I was able to build the `example_01_basic_app.nim` on Arch linux, using mingw64 and Nim 0.19.9 with command `nim c -d:mingw --app:gui example_01_basic_app.nim`. 

Perhaps your version of mingw is 32bit?

**Comment by trustable-code** [comment]
appearently no longer relevant, please re-open if still reproducible
