### ISSUE TITLE
[Suggestion] GUI builder

### ISSUE THREAD

**Issue by TiberiumN** [trustable-code/NiGui#4]
I think it would be possible to create GUI editor, so you can design GUI with simple WYSIWYG interface at least with exact controls positions (not with automatic controls placing)

**Comment by trustable-code** [comment]
Reasons why I think it's not a good idea (at least for now):
- I don't like the concept of GUI editors, so I won't create one.
- Static control positioning is bad for user experience and should not be used.
- NiGui is in a too early stage.
- I think it takes a lot of effort to create a GUI editor. Maybe look at https://www.lazarus-ide.org/ to get an idea about it.

**Comment by TiberiumN** [comment]
@trustable-code thanks, now I see why it's a bad idea

**Comment by TiberiumN** [comment]
@trustable-code sorry for offtopic, but how can I make text area read-only?
