### ISSUE TITLE
Wrong Code for example_02_controls.nim in Windows

### ISSUE THREAD

**Issue by aryanbadiee** [trustable-code/NiGui#41]
Hi
in https://github.com/trustable-code/NiGui/blob/8b88552444215852f5fe999091d55dc12bd4313f/examples/example_02_controls.nim#L25 "\n" do not go to the new line for textArea in Windows!
replace "\n" with "\p" or "\r\n".
thanks and good luck.

**Comment by trustable-code** [comment]
You are right. Thanks.
