### ISSUE TITLE
Compile fails fSystemDpi  

### ISSUE THREAD

**Issue by qqtop** [trustable-code/NiGui#45]
```
/.nimble/pkgs/nigui-0.1.1/nigui.nim(1067, 41) Error: cannot evaluate at compile time: fSystemDpi
```

Os   : linux
Nim : latest devel

**Comment by trustable-code** [comment]
Do you call ``scaleToDpi()`` in your program? I wonder where it is used at compile time.

**Comment by qqtop** [comment]
No . The issue seems to appear when importing msgbox .

100.scaleToDpi     seems to fail.

**Comment by trustable-code** [comment]
With "const" -> "let" it should work again.

**Comment by qqtop** [comment]
Looks good again. Thank you.
