### ISSUE TITLE
I loved Nigui, it is small and easy, issue with e.g.10

### ISSUE THREAD

**Issue by sk-Prime** [trustable-code/NiGui#48]
i tried some examples. key feature i liked  nigui because
1.  very fast compile time
2.  small executable
3.  easy to learn
please make it complete. the issue is example 10 compile perfectly but in execution time it raise an error. windows 7
![Capture](https://user-images.githubusercontent.com/26684644/63991798-b56ebe00-cb1b-11e9-8439-52a632734bb7.PNG)

**Comment by sk-Prime** [comment]
i compile it again and it is working.

**Comment by trustable-code** [comment]
Do you know, what the issue was?

**Comment by sk-Prime** [comment]
i compiled multiple times, but every time when i was going to run that program the above error appears.
the reason behind (i investigate now after your question)
1. i copied the source code and paste the code in `nigui_text.nim`
2. it compiled properly, but in run-time the program can not locate this `example_01_basic_app.png` file. because it was not in directory.
-
so, is it possible to raise `file not found error :  can not locate example_01_basic_app.png` instead of above error.

**Comment by trustable-code** [comment]
I have improved the error message. In your case it should show now "file does not exist".
