### ISSUE TITLE
TextBox doesn't support unicode 

### ISSUE THREAD

**Issue by drthinh** [trustable-code/NiGui#59]
Controls display unicode well from coding but TextBox couldn't type unicode characters

**Comment by trustable-code** [comment]
What character do you type and what is the platform?

**Comment by drthinh** [comment]
Thanks for your reply,
Sorry about my short question. I compiled a small program using NiGui, displaying Unicode text by code were ok, but when I type unicode in TextBox, it only showed "??" characters. I'm using Vietnamese language in Windows 10 64 bit.
Example 
![Capture](https://user-images.githubusercontent.com/37505897/64540684-c359e580-d34a-11e9-96fa-16916b7ec71f.JPG)

**Comment by trustable-code** [comment]
How to reproduce without using the keyboard:
1. Open `example_02_controls.exe`
2. Focus the text box
3. Run `unicodeinput.exe` (download from https://www.fileformat.info/tool/unicodeinput/index.htm)
4. Enter the unicode value `1E9E`
5. Click "Send"

Result: A "?" character appears in the NiGui text box.
Expected result: A "ß" character appears in the NiGui text box.

**Comment by trustable-code** [comment]
@drthinh Does it work for you with my latest commit?
