### ISSUE TITLE
Add a nim.cfg file to examples

### ISSUE THREAD

**Issue by PMunch** [trustable-code/NiGui#6]
It is mentioned in the readme that a `--path` should be set in your Nim config for the nigui files. It would be nice if the examples folder had a nim.cfg with `--path:"../src"` in it so people had an example for how to do that.

**Comment by trustable-code** [comment]
I just improved the text. I think an extra example file is not needed, because it's just one line.
What do you think now?

**Comment by PMunch** [comment]
Yeah I guess that works. It's just nice when you can cd into a folder and run "nim c -r" and have it run.

**Comment by trustable-code** [comment]
I will close this, if someone really does not get it to work, we can improve the docs further.
