### ISSUE TITLE
TextBox not editable when compiling with -d:release

### ISSUE THREAD

**Issue by qqtop** [trustable-code/NiGui#62]
After compiling with Nim v1.0 and 1.0.99 on linux I note following issues:

 1.  If compiled with -d:release or -d:danger textArea or textBox do not allow input

 2.  If there are several  events like this

```
            window.onKeyDown = proc(event: KeyboardEvent) =
            # Ctrl + F -> Focus on inputBox
              if Key_F.isDown() and Key_ControlL.isDown():
                 inputTextBox.focus()

            window.onKeyDown = proc(event: KeyboardEvent) =
            # Ctrl + Q -> Quit application  
              if Key_Q.isDown() and Key_ControlL.isDown():
                  doFinish()
```

      Only the last one will actually be executed  , the others seem to do nothing.

**Comment by trustable-code** [comment]
1. Seems to be bug, I will test it later.
2. This is normal, because in your example you overwrite ``window.onKeyDown`` in the second assignment.

**Comment by trustable-code** [comment]
After first look: It's a bug in the Nim compiler. It also happens with the latest devel version.
I'm going to investigate further.

**Comment by qqtop** [comment]
I also looked at it , but did not see anything immediate suspicious.
By the way, thanks for a nice framework !

**Comment by qqtop** [comment]
If compile with :    {.optimization: speed.}      input it is ok
If compile with :   {.optimization: size.}          input fails

**Comment by trustable-code** [comment]
I figured it out: A callback proc in NiGui uses ``bool`` as result type, which has not the expected size. I have added the type ``Gboolean`` and related result types.
