### ISSUE TITLE
"could not load: libgtk-x11-3.0.dylib" on macOS

### ISSUE THREAD

**Issue by abulka** [trustable-code/NiGui#63]
Calc seemed to build ok on Mac, but couldn't run because of a missing libgtk library. Is there any solution for this?

```
Hint:  [Link]
Hint: operation successful (44662 lines compiled; 4.632 sec total; 72.336MiB peakmem; Debug Build) [SuccessX]
Hint: /Users/Andy/Devel/nim_demos/NiCalc/src/NiCalc  [Exec]
could not load: libgtk-x11-3.0.dylib
compile with -d:nimDebugDlOpen for more information
Error: execution of an external program failed: '/Users/Andy/Devel/nim_demos/NiCalc/src/NiCalc '
```

**Comment by dcurrie** [comment]
Using homebrew the gtk+3 library is installed in
`/usr/local/Cellar/gtk+3/3.24.9/lib/libgtk-3.0.dylib`

Somehow, NiGui seems to find it if I build with `-d:gtk_quartz` as in
`nim c -d:gtk_quartz -r nidraw.nim`

**Comment by deeuu** [comment]
Can confirm `-d:gtk_quartz` works on macOS Catalina.

**Comment by trustable-code** [comment]
I changed the filename used on macOS to the one used for `-d:gtk_quartz`: Now it should find the library without compiling with `-d:gtk_quartz`. I assume the other filename is not needed. 
If any problem occurs, please reopen.
