### ISSUE TITLE
Windows: fileDialog.title has no effect

### ISSUE THREAD

**Issue by WilliamDraco** [trustable-code/NiGui#66]
```
var dialog = newOpenFileDialog()
dialog.title = "This has no effect on Windows"
```
Also affects newSaveFileDialog() on Windows 10, compiled with nim 1.0.0

Example 12 includes both a save and open dialog, neither of which produce the correct dialog box title, default to "Open" and "Save".

**Comment by trustable-code** [comment]
@WilliamDraco Thanks for reporting :-)
