### ISSUE TITLE
how to get the window pos and size?

### ISSUE THREAD

**Issue by mark-summerfield** [trustable-code/NiGui#82]
I have a ``Window`` and can set its ``width`` and ``height``. But when I try to get is position or size, e.g., ``let x = mainwindow.x`` I get an error:
```
config.nim(65, 24) Error: undeclared field: 'x' for type nigui.Window [declared in /home/mark/.nimble/pkgs/nigui-0.2.2/nigui.nim(215, 3)] 
```
What puzzles me is that ``x`` does appear to be a public field.
I'd like to be able to get/set the size and pos so that I can load/save them for the user.

**Comment by trustable-code** [comment]
This works for me unter Linux and Windows:
```nim
var window = newWindow()
window.x = window.x + 20
```
Can you show a small program to reproduce the error?

**Comment by mark-summerfield** [comment]
As your small program shows, a small program doesn't produce the error.
I plan to release a game written in pure nim/nigui with the load/save of window size/pos commented out (since it exhibits this bug) and I'll try to remember to add a link to it then.

**Comment by mark-summerfield** [comment]
Sorry, it was my bug not yours.
