### ISSUE TITLE
Prolonged use has caused corruption of the win32 API

### ISSUE THREAD

**Issue by rockcavera** [trustable-code/NiGui#91]
I'm not sure what I'm going to talk about and I don't even know if that's the problem. But I made a program that does a long scan and the Windows API for the interface seems to corrupt, to the point that any other program that uses the interface gets corrupted, solving the problem only after restarting Windows.

You can ask me: how does it corrupt the Windows API? Well, the answer is a little complicated. After some time running, I notice that the gray background of the dialog turns white and the next event in the program ends up making it close without warning. In this way, all the running programs and even explorer.exe are strange. You can see the edges of the windows, but you cannot see the contents. Windows hangs. Just restarting Windows to resolve.

I don't know if I'm using it wrong, because I create a button that does a long check, leaving the program dialog on the main thread and creating a child thread to perform the heavy task. In this, I use app.sleep until the child thread ends. Thus, I prevent the main dialog from getting stuck.

A pseudo code:
```nim
button_check.onClick = proc(event: ClickEvent) =
  button_other.enabled = false
  button_abort.enabled = true

  var thr: Thread[void]

  createThread(thr, check)

  while running(thr):
    app.sleep(1000)
```

The problem occurs after about 30 minutes of execution.

I will provide a 10x accelerated video for you to view the problem. [Download video problem here](https://drive.google.com/file/d/1Q-c1_4GgvCxYWwAMETQYKZ7BraBi0hvY/view)
The problem occurs at minute 4:25.
At 5:50 I show how this problem affects other programs.

Was compiled with -d:danger -d:release --threads:on --app:gui

**Comment by 0xACE** [comment]
I'm not on windows and can't test it out atm. + `problem.7z` doesn't seem to extract on my machine yielding: `ERROR: Unsupported Method : problem.mp4`

**Comment by trustable-code** [comment]
I can't extract the archive file too. So I think the file is corrupted.
But the WinAPI issue occures rarely with my own programs too.

**Comment by rockcavera** [comment]
> I'm not on windows and can't test it out atm. + `problem.7z` doesn't seem to extract on my machine yielding: `ERROR: Unsupported Method : problem.mp4`

> I can't extract the archive file too. So I think the file is corrupted.
> But the WinAPI issue occures rarely with my own programs too.

The upload from my internet is not very good, so I compressed it with 7-zip. As you were not able to unzip, I uploaded the video directly: [download one to watch the video here](https://drive.google.com/file/d/1Q-c1_4GgvCxYWwAMETQYKZ7BraBi0hvY/view?usp=sharing).

**Comment by trustable-code** [comment]
@rockcavera Thanks for posting the video and the bug report. So far I don't know how to solve it, but I will search on the Internet.

**Comment by 0xACE** [comment]
@rockcavera thanks for the re-upload.

I haven't used Windows for many years. But I do recall seeing a similar issue when the compositor was running, but I'm not even sure if windows supports turning it off these days... Maybe restarting the compositor should suffice?

Other than that I really shouldn't comment unless I test it personally.

**Comment by trustable-code** [comment]
Should be fixed now. If the issue still occurs for you, please re-open.

**Comment by rockcavera** [comment]
> Should be fixed now. If the issue still occurs for you, please re-open.

I took the test here and apparently the problem was solved. Thanks.
